name = "Crouton"
author = "Flarefin"
link = ""
year = 2022

[formats.standard]
matrix = [["g", "l", "d", "p", "q", "z", "k", "o", "u", ","],
["c", "r", "t", "n", "v", "y", "h", "a", "e", "i"],
["w", "j", "m", "b", " ", " ", "x", "'", ";", "."],
[" ", " ", " ", " ", " ", "f", "s"]]

map = {}
home_row = 1
thumb_row = 3
