name = "CTGAP"
author = "Colby Chai"
link = "github.com/CTGAP/ctgap-keyboard-layout"
year = 2022

[formats.standard]
matrix = [["q", "p", "l", "c", "j", "x", "f", "o", "u", "/"],
["r", "n", "t", "s", "g", "y", "h", "e", "i", "a"],
["z", "b", "m", "w", "v", "k", "d", "'", ",", "."]]

map = {}
home_row = 1
