name = "Dvorak (UK Punctuation)"
author = "Toby Dickenson"
link = ""
year = 2008

[formats.standard]
matrix = [["/", ",", ".", "p", "y", "f", "g", "c", "r", "l", "[", "]"],
["a", "o", "e", "u", "i", "d", "h", "t", "n", "s", "'", "#"],
[";", "q", "j", "k", "x", "b", "m", "w", "v", "z"]]

map = {}
home_row = 1
