name = "Radish"
author = "Qwertron"
link = "https://discord.com/channels/807843650717483049/807844118826975262/980842532600705064"
year = 2022

[formats.standard]
matrix = [["v", "c", "w", "f", "q", "z", "p", "u", "o", "y", "/", "="],
["r", "d", "s", "h", "l", "k", "t", "e", "a", "i", "-"],
["x", "j", "m", "n", ";", "b", "g", "'", ",", "."]]

map = {}
home_row = 1
