name = "Ridge"
author = "Flarefin"
link = ""
year = 2022

[formats]
angle_preferred = true
[formats.angle]
matrix = [["v", "m", "l", "w", "q", "z", "x", "o", "u", ","],
["s", "t", "r", "d", "g", "f", "n", "a", "e", "i"],
["k", "j", "p", "c", " ", "b", "h", "'", ";", "."],
[" ", " ", " ", " ", " ", " ", "y"]]

map = {}
home_row = 1